services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

    volumes:
      - ./backend:/app
    networks:
      - nasa_nework
    command: ["gunicorn", "-c", "./gunicorn/gunicorn.config.py", "wsgi:app"]

  nginx:
    extends:
      file: ./nginx/service.yml
      service: nginx
    ports:
      - "80:80"
    networks:
      - nasa_nework

    depends_on:
      - backend

networks:
  nasa_nework:
    name: nasa_nework
