services:
  nginx:
    image: nginx:1.27.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./conf.d
        target: /etc/nginx/conf.d
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./certbot
        target: /etc/nginx/ssl
